# Generated by Django 5.2.17 on 2026-09-19 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0035_match_announced_added_minutes_match_clock_version_and_more'),
        ('teams', '0005_team_head_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('groups', 'Fase de grupos'), ('knockout', 'Eliminatorias'), ('third_place', 'Tercer puesto')], max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=20)),
                ('qualifying_teams', models.PositiveSmallIntegerField(default=2)),
                ('matchdays', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='tournaments.phase')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('matchday', models.PositiveSmallIntegerField(default=1)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_fixture', to='matches.match')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='tournaments.group')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='tournaments.phase')),
            ],
            options={
                'ordering': ['phase__order', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('teams', models.ManyToManyField(blank=True, related_name='tournament_seasons', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='tournaments.season'),
        ),
        migrations.CreateModel(
            name='GroupEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tournaments.group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
                ('phase', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='tournaments.phase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('phase', 'team'), name='unique_team_per_group_phase')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('phase', 'name'), name='unique_phase_group_name'),
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.UniqueConstraint(fields=('phase', 'position'), name='unique_phase_fixture_position'),
        ),
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(fields=('season', 'order'), name='unique_season_phase_order'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_tournament_season'),
        ),
    ]
