# Generated by Django 5.2.17 on 2026-09-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='phase',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'third_place')), fields=('season',), name='unique_season_third_place'),
        ),
    ]
