# Generated by Django 5.2.17 on 2026-09-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_phase_unique_season_third_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams_per_group',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('max_teams_per_group__gte', 1)), name='tournament_positive_group_capacity'),
        ),
    ]
