# Generated by Django 5.2.17 on 2026-09-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_max_teams_per_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tie_break_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='phase',
            name='expected_matches',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='source_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='tournaments.phase'),
        ),
    ]
