# Generated by Django 5.2.17 on 2026-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_group_tie_break_order_phase_expected_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/logos/'),
        ),
    ]
