# Generated by Django 5.2.17 on 2026-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_news_published_at_news_scheduled_at_news_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="preview",
            field=models.CharField(blank=True, default="", max_length=320),
        ),
    ]
