# Generated by Django 5.2.17 on 2026-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='preferred_position',
            field=models.CharField(blank=True, choices=[('goalkeeper', 'Goalkeeper'), ('right_back', 'Right Back'), ('center_back', 'Center Back'), ('left_back', 'Left Back'), ('sweeper', 'Sweeper'), ('right_wing_back', 'Right Wing Back'), ('left_wing_back', 'Left Wing Back'), ('defensive_midfielder', 'Defensive Midfielder'), ('central_midfielder', 'Central Midfielder'), ('attacking_midfielder', 'Attacking Midfielder'), ('right_midfielder', 'Right Midfielder'), ('left_midfielder', 'Left Midfielder'), ('right_winger', 'Right Winger'), ('left_winger', 'Left Winger'), ('second_striker', 'Second Striker'), ('center_forward', 'Center Forward')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_shirt_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_position__isnull', True), ('preferred_position__in', ['goalkeeper', 'right_back', 'center_back', 'left_back', 'sweeper', 'right_wing_back', 'left_wing_back', 'defensive_midfielder', 'central_midfielder', 'attacking_midfielder', 'right_midfielder', 'left_midfielder', 'right_winger', 'left_winger', 'second_striker', 'center_forward']), _connector='OR'), name='valid_player_preferred_position'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_shirt_number__isnull', True), models.Q(('preferred_shirt_number__gte', 1), ('preferred_shirt_number__lte', 99)), _connector='OR'), name='valid_player_preferred_shirt_number'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(condition=models.Q(('preferred_shirt_number__isnull', False)), fields=('team', 'preferred_shirt_number'), name='unique_player_preferred_shirt_per_team'),
        ),
    ]
