# Generated by Django 5.2.17 on 2026-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='head_coach_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
