# Generated by Django 5.2.17 on 2026-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_head_coach_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='crest',
            field=models.ImageField(blank=True, null=True, upload_to='teams/crests/'),
        ),
        migrations.AddField(
            model_name='team',
            name='founded_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='stadium_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('founded_year__isnull', True), ('founded_year__gte', 1800), _connector='OR'), name='team_valid_founded_year'),
        ),
    ]
