# Generated by Django 5.2.17 on 2026-09-21 20:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('activity_version', models.PositiveBigIntegerField(default=0)),
                ('processed_version', models.PositiveBigIntegerField(default=0)),
                ('next_refresh_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'recommendation_visitors',
            },
        ),
        migrations.CreateModel(
            name='InterestProfile',
            fields=[
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommendations.visitor')),
                ('team_weights', models.JSONField(default=dict)),
                ('tournament_weights', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'recommendation_interest_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecommendationSnapshot',
            fields=[
                ('key', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('sections', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('visitor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.visitor')),
            ],
            options={
                'db_table': 'recommendation_snapshots',
            },
        ),
        migrations.CreateModel(
            name='NavigationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('navigation_id', models.UUIDField()),
                ('content_kind', models.CharField(choices=[('team', 'Team'), ('player', 'Player'), ('news', 'News'), ('match', 'Match'), ('tournament', 'Tournament')], max_length=20)),
                ('content_id', models.UUIDField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counts_as_visit', models.BooleanField(default=True)),
                ('active_seconds', models.PositiveSmallIntegerField(default=0)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='recommendations.visitor')),
            ],
            options={
                'db_table': 'recommendation_navigation_activities',
                'indexes': [models.Index(fields=['visitor', 'occurred_at'], name='navigation_visitor_time'), models.Index(fields=['occurred_at'], name='navigation_retention')],
                'constraints': [models.CheckConstraint(condition=models.Q(('active_seconds__lte', 120)), name='navigation_active_seconds_limit'), models.UniqueConstraint(fields=('visitor', 'navigation_id'), name='unique_visitor_navigation'), models.CheckConstraint(condition=models.Q(('content_kind__in', ['team', 'player', 'news', 'match', 'tournament'])), name='valid_navigation_content_kind')],
            },
        ),
    ]
