# Generated by Django 5.2.17 on 2026-08-29 12:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("home_team_name", models.CharField(max_length=200)),
                ("away_team_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("finished", "Finished"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-scheduled_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["scheduled", "live", "finished"])),
                        name="valid_match_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("home_team_name", ""), _negated=True),
                            models.Q(("away_team_name", ""), _negated=True),
                        ),
                        name="match_team_names_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("home_team_name", models.F("away_team_name")), _negated=True
                        ),
                        name="match_teams_are_different",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finished_at__isnull", True),
                                ("started_at__isnull", True),
                                ("status", "scheduled"),
                            ),
                            models.Q(
                                ("finished_at__isnull", True),
                                ("started_at__isnull", False),
                                ("status", "live"),
                            ),
                            models.Q(
                                ("finished_at__isnull", False),
                                ("started_at__isnull", False),
                                ("status", "finished"),
                            ),
                            _connector="OR",
                        ),
                        name="valid_match_lifecycle_timestamps",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("finished_at__isnull", True),
                            ("finished_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="match_finish_after_start",
                    ),
                ],
            },
        ),
    ]
