# Generated by Django 5.2.17 on 2026-08-29 12:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "team_side",
                    models.CharField(choices=[("home", "Home"), ("away", "Away")], max_length=10),
                ),
                ("player_name", models.CharField(max_length=200)),
                (
                    "card_type",
                    models.CharField(choices=[("yellow", "Yellow"), ("red", "Red")], max_length=10),
                ),
                ("minute", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "db_table": "match_cards",
                "ordering": ["minute", "created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("team_side__in", ["home", "away"])),
                        name="valid_card_team_side",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("card_type__in", ["yellow", "red"])),
                        name="valid_card_type",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minute__gte", 0), ("minute__lte", 130)),
                        name="valid_card_minute",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("player_name", ""), _negated=True),
                        name="card_player_name_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "team_side",
                    models.CharField(choices=[("home", "Home"), ("away", "Away")], max_length=10),
                ),
                ("player_name", models.CharField(max_length=200)),
                ("minute", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "db_table": "match_goals",
                "ordering": ["minute", "created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("team_side__in", ["home", "away"])),
                        name="valid_goal_team_side",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minute__gte", 0), ("minute__lte", 130)),
                        name="valid_goal_minute",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("player_name", ""), _negated=True),
                        name="goal_player_name_not_empty",
                    ),
                ],
            },
        ),
    ]
