# Generated by Django 5.2.17 on 2026-08-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_match_lineup_player'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchlineupplayer',
            name='role',
            field=models.CharField(choices=[('starter', 'Starter'), ('substitute', 'Substitute')], default='starter', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='matchlineupplayer',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['starter', 'substitute'])), name='valid_match_squad_role'),
        ),
        migrations.AddConstraint(
            model_name='matchlineupplayer',
            constraint=models.CheckConstraint(condition=models.Q(('is_captain', False), ('role', 'starter'), _connector='OR'), name='match_captain_must_be_starter'),
        ),
    ]
