# Generated by Django 5.2.17 on 2026-08-31 14:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


def put_starters_on_field(apps, schema_editor):
    squad_player = apps.get_model("matches", "MatchSquadPlayer")
    squad_player.objects.filter(role="starter").update(is_on_field=True)


def clear_on_field_state(apps, schema_editor):
    squad_player = apps.get_model("matches", "MatchSquadPlayer")
    squad_player.objects.update(is_on_field=False)


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_rename_match_lineup_player_to_match_squad_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsquadplayer',
            name='is_on_field',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(put_starters_on_field, clear_on_field_state),
        migrations.CreateModel(
            name='MatchSubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('minute', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='matches.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_in', to='matches.matchsquadplayer')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitutions_out', to='matches.matchsquadplayer')),
            ],
            options={
                'db_table': 'match_substitutions',
                'ordering': ['minute', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_substitution_team_side'), models.CheckConstraint(condition=models.Q(('minute__gte', 0), ('minute__lte', 130)), name='valid_substitution_minute'), models.CheckConstraint(condition=models.Q(('player_out', models.F('player_in')), _negated=True), name='substitution_players_are_different')],
            },
        ),
    ]
