# Generated by Django 5.2.17 on 2026-08-31 19:11

from django.db import migrations, models


def populate_match_clock(apps, schema_editor):
    Match = apps.get_model("matches", "Match")
    Match.objects.filter(status="live", current_period="first_half").update(
        current_minute=1
    )
    Match.objects.filter(status="live", current_period="halftime").update(
        current_minute=45
    )
    Match.objects.filter(status="live", current_period="second_half").update(
        current_minute=46
    )
    Match.objects.filter(status="finished").update(current_minute=90)


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_official_match_periods'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='valid_match_lifecycle_timestamps',
        ),
        migrations.AddField(
            model_name='match',
            name='current_added_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='current_minute',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_match_clock, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_minute__isnull', True), ('current_period__isnull', True)), models.Q(('current_minute__gte', 1), ('current_minute__lte', 45), ('current_period', 'first_half')), models.Q(('current_minute', 45), ('current_period', 'halftime')), models.Q(('current_minute__gte', 46), ('current_minute__lte', 90), ('current_period', 'second_half')), _connector='OR'), name='valid_match_clock_period'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('current_added_minute', 0), ('current_minute__in', [45, 90]), _connector='OR'), name='valid_match_clock_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_added_minute', 0), ('current_minute__isnull', True), ('current_period__isnull', True), ('finished_at__isnull', True), ('started_at__isnull', True), ('status', 'scheduled')), models.Q(('current_minute__isnull', False), ('current_period__in', ['first_half', 'halftime', 'second_half']), ('finished_at__isnull', True), ('started_at__isnull', False), ('status', 'live')), models.Q(('current_minute', 90), ('current_period', 'second_half'), ('finished_at__isnull', False), ('started_at__isnull', False), ('status', 'finished')), _connector='OR'), name='valid_match_lifecycle_timestamps'),
        ),
    ]
