# Generated by Django 5.2.17 on 2026-09-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_remove_match_valid_match_lifecycle_timestamps_and_more'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsquadplayer',
            name='is_sent_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='matchsquadplayer',
            constraint=models.CheckConstraint(condition=models.Q(('is_sent_off', False), ('is_on_field', False), _connector='OR'), name='sent_off_player_must_be_off_field'),
        ),
    ]
