# Generated by Django 5.2.17 on 2026-09-04 17:33

from django.db import migrations, models


def classify_existing_expulsions(apps, schema_editor):
    MatchSquadPlayer = apps.get_model("matches", "MatchSquadPlayer")
    MatchSquadPlayer.objects.filter(is_sent_off=True).update(
        sent_off_reason="direct_red"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_matchsquadplayer_is_sent_off_and_more'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsquadplayer',
            name='sent_off_reason',
            field=models.CharField(blank=True, choices=[('direct_red', 'Direct Red'), ('second_yellow', 'Second Yellow')], max_length=20, null=True),
        ),
        migrations.RunPython(
            classify_existing_expulsions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='matchsquadplayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_sent_off', False), ('sent_off_reason__isnull', True)), models.Q(('is_sent_off', True), ('sent_off_reason__in', ['direct_red', 'second_yellow'])), _connector='OR'), name='valid_player_sent_off_reason'),
        ),
    ]
