# Generated by Django 5.2.17 on 2026-09-05 15:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0023_matchsquadplayer_sent_off_reason_and_more'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyShootout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='in_progress', max_length=20)),
                ('home_score', models.PositiveSmallIntegerField(default=0)),
                ('away_score', models.PositiveSmallIntegerField(default=0)),
                ('winner_team_side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=10, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'penalty_shootouts',
            },
        ),
        migrations.CreateModel(
            name='PenaltyShootoutKick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=200)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('scored', 'Scored'), ('missed', 'Missed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'penalty_shootout_kicks',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('penalty', 'Penalty')], default='regular', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('goal_type__in', ['regular', 'penalty'])), name='valid_goal_type'),
        ),
        migrations.AddField(
            model_name='penaltyshootout',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_shootout', to='matches.match'),
        ),
        migrations.AddField(
            model_name='penaltyshootoutkick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_shootout_kicks', to='teams.player'),
        ),
        migrations.AddField(
            model_name='penaltyshootoutkick',
            name='shootout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kicks', to='matches.penaltyshootout'),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootout',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'finished'])), name='valid_penalty_shootout_status'),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootout',
            constraint=models.CheckConstraint(condition=models.Q(('winner_team_side__isnull', True), ('winner_team_side__in', ['home', 'away']), _connector='OR'), name='valid_penalty_shootout_winner'),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootoutkick',
            constraint=models.UniqueConstraint(fields=('shootout', 'sequence_number'), name='unique_penalty_shootout_kick_sequence'),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootoutkick',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_penalty_shootout_kick_team_side'),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootoutkick',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['scored', 'missed'])), name='valid_penalty_shootout_kick_outcome'),
        ),
    ]
