# Generated by Django 5.2.17 on 2026-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_penaltyshootout_penaltyshootoutkick_goal_goal_type_and_more'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='valid_card_minute',
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='valid_card_period_minute',
        ),
        migrations.RemoveConstraint(
            model_name='card',
            name='valid_card_added_minute',
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='valid_goal_minute',
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='valid_goal_period_minute',
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='valid_goal_added_minute',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='valid_match_period',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='valid_match_clock_period',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='valid_match_clock_added_minute',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='valid_match_lifecycle_timestamps',
        ),
        migrations.RemoveConstraint(
            model_name='matchsubstitution',
            name='valid_substitution_minute',
        ),
        migrations.RemoveConstraint(
            model_name='matchsubstitution',
            name='valid_substitution_period_minute',
        ),
        migrations.RemoveConstraint(
            model_name='matchsubstitution',
            name='valid_substitution_added_minute',
        ),
        migrations.AlterField(
            model_name='card',
            name='period',
            field=models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25),
        ),
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25),
        ),
        migrations.AlterField(
            model_name='match',
            name='current_period',
            field=models.CharField(blank=True, choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='matchsubstitution',
            name='period',
            field=models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_card_minute'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_card_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_card_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_goal_minute'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_goal_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_goal_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('current_period__isnull', True), ('current_period__in', ['first_half', 'halftime', 'second_half', 'extra_time_first_half', 'extra_time_halftime', 'extra_time_second_half']), _connector='OR'), name='valid_match_period'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_minute__isnull', True), ('current_period__isnull', True)), models.Q(('current_minute__gte', 1), ('current_minute__lte', 45), ('current_period', 'first_half')), models.Q(('current_minute', 45), ('current_period', 'halftime')), models.Q(('current_minute__gte', 46), ('current_minute__lte', 90), ('current_period', 'second_half')), models.Q(('current_minute__gte', 91), ('current_minute__lte', 105), ('current_period', 'extra_time_first_half')), models.Q(('current_minute', 105), ('current_period', 'extra_time_halftime')), models.Q(('current_minute__gte', 106), ('current_minute__lte', 120), ('current_period', 'extra_time_second_half')), _connector='OR'), name='valid_match_clock_period'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('current_added_minute', 0), ('current_minute__in', [45, 90, 105, 120]), _connector='OR'), name='valid_match_clock_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('current_added_minute', 0), ('current_minute__isnull', True), ('current_period__isnull', True), ('finished_at__isnull', True), ('started_at__isnull', True), ('status', 'scheduled')), models.Q(('current_minute__isnull', False), ('current_period__in', ['first_half', 'halftime', 'second_half', 'extra_time_first_half', 'extra_time_halftime', 'extra_time_second_half']), ('finished_at__isnull', True), ('started_at__isnull', False), ('status', 'live')), models.Q(('current_minute__in', [90, 120]), ('current_period__in', ['second_half', 'extra_time_second_half']), ('finished_at__isnull', False), ('started_at__isnull', False), ('status', 'finished')), _connector='OR'), name='valid_match_lifecycle_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='matchsubstitution',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_substitution_minute'),
        ),
        migrations.AddConstraint(
            model_name='matchsubstitution',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_substitution_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='matchsubstitution',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_substitution_added_minute'),
        ),
    ]
