# Generated by Django 5.2.17 on 2026-09-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0025_remove_card_valid_card_minute_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='penaltyshootout',
            name='valid_penalty_shootout_status',
        ),
        migrations.RemoveConstraint(
            model_name='penaltyshootout',
            name='valid_penalty_shootout_winner',
        ),
        migrations.AddField(
            model_name='penaltyshootout',
            name='away_kick_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penaltyshootout',
            name='home_kick_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='penaltyshootout',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('decided', 'Decided'), ('finished', 'Finished')], default='in_progress', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootout',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['in_progress', 'decided', 'finished'])), name='valid_penalty_shootout_status'),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'in_progress'), ('winner_team_side__isnull', True)), models.Q(('status__in', ['decided', 'finished']), ('winner_team_side__in', ['home', 'away'])), _connector='OR'), name='valid_penalty_shootout_winner'),
        ),
    ]
