# Generated by Django 5.2.17 on 2026-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0026_remove_penaltyshootout_valid_penalty_shootout_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyshootout',
            name='starting_team_side',
            field=models.CharField(choices=[('home', 'Home'), ('away', 'Away')], default='home', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootout',
            constraint=models.CheckConstraint(condition=models.Q(('starting_team_side__in', ['home', 'away'])), name='valid_penalty_shootout_starting_team_side'),
        ),
    ]
