# Generated by Django 5.2.17 on 2026-09-07 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0027_penaltyshootout_starting_team_side_and_more'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyShootoutParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_shootout_participations', to='teams.player')),
                ('shootout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.penaltyshootout')),
            ],
            options={
                'db_table': 'penalty_shootout_participants',
                'constraints': [models.UniqueConstraint(fields=('shootout', 'player'), name='unique_penalty_shootout_participant'), models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_penalty_shootout_participant_team_side')],
            },
        ),
    ]
