# Generated by Django 5.2.17 on 2026-09-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0028_penaltyshootoutparticipant'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyshootoutparticipant',
            name='became_ineligible_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penaltyshootoutparticipant',
            name='ineligibility_reason',
            field=models.CharField(blank=True, choices=[('initial_equalization', 'Initial Equalization'), ('injury', 'Injury'), ('sent_off', 'Sent Off'), ('opponent_reduction', 'Opponent Reduction')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='penaltyshootoutparticipant',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='penaltyshootoutparticipant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('became_ineligible_at__isnull', True), ('ineligibility_reason__isnull', True), ('is_eligible', True)), models.Q(('became_ineligible_at__isnull', False), ('ineligibility_reason__in', ['initial_equalization', 'injury', 'sent_off', 'opponent_reduction']), ('is_eligible', False)), _connector='OR'), name='valid_penalty_shootout_participant_eligibility'),
        ),
    ]
