# Generated by Django 5.2.17 on 2026-09-10 22:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0029_penaltyshootoutparticipant_became_ineligible_at_and_more'),
        ('teams', '0004_player_preferred_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_injuries',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('outcome', models.CharField(choices=[('missed', 'Missed'), ('saved', 'Saved'), ('hit_post', 'Hit Post')], max_length=10)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_penalty_attempts',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VarReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('reason', models.CharField(choices=[('goal', 'Goal'), ('penalty', 'Penalty'), ('direct_red_card', 'Direct Red Card'), ('mistaken_identity', 'Mistaken Identity')], max_length=20)),
                ('decision', models.CharField(choices=[('confirmed', 'Confirmed'), ('overturned', 'Overturned'), ('changed', 'Changed')], max_length=10)),
                ('reviewed_event_id', models.UUIDField(blank=True, null=True)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_var_reviews',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='goal',
            name='valid_goal_type',
        ),
        migrations.AddField(
            model_name='goal',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assisted_goals', to='teams.player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='assist_player_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('penalty', 'Penalty'), ('own_goal', 'Own Goal')], default='regular', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('goal_type__in', ['regular', 'penalty', 'own_goal'])), name='valid_goal_type'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assist_player__isnull', True), ('assist_player_name__isnull', True)), models.Q(('assist_player__isnull', False), ('assist_player_name__isnull', False)), _connector='OR'), name='valid_goal_assist_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('goal_type', 'regular'), ('assist_player__isnull', True), _connector='OR'), name='assist_only_for_regular_goal'),
        ),
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.CheckConstraint(condition=models.Q(('assist_player__isnull', True), models.Q(('assist_player', models.F('player')), _negated=True), _connector='OR'), name='goal_scorer_and_assistant_different'),
        ),
        migrations.AddField(
            model_name='injury',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='matches.match'),
        ),
        migrations.AddField(
            model_name='injury',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injuries', to='teams.player'),
        ),
        migrations.AddField(
            model_name='penaltyattempt',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_attempts', to='matches.match'),
        ),
        migrations.AddField(
            model_name='penaltyattempt',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_attempts', to='teams.player'),
        ),
        migrations.AddField(
            model_name='varreview',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='var_reviews', to='matches.match'),
        ),
        migrations.AddConstraint(
            model_name='injury',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_injury_team_side'),
        ),
        migrations.AddConstraint(
            model_name='injury',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_injury_minute'),
        ),
        migrations.AddConstraint(
            model_name='injury',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_injury_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='injury',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_injury_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='injury',
            constraint=models.CheckConstraint(condition=models.Q(('player_name', ''), _negated=True), name='injury_player_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='penaltyattempt',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_penalty_attempt_team_side'),
        ),
        migrations.AddConstraint(
            model_name='penaltyattempt',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_penalty_attempt_minute'),
        ),
        migrations.AddConstraint(
            model_name='penaltyattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_penalty_attempt_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='penaltyattempt',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_penalty_attempt_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='penaltyattempt',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['missed', 'saved', 'hit_post'])), name='valid_penalty_attempt_outcome'),
        ),
        migrations.AddConstraint(
            model_name='penaltyattempt',
            constraint=models.CheckConstraint(condition=models.Q(('player_name', ''), _negated=True), name='penalty_attempt_player_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='varreview',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_var_review_team_side'),
        ),
        migrations.AddConstraint(
            model_name='varreview',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_var_review_minute'),
        ),
        migrations.AddConstraint(
            model_name='varreview',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_var_review_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='varreview',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_var_review_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='varreview',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['goal', 'penalty', 'direct_red_card', 'mistaken_identity'])), name='valid_var_review_reason'),
        ),
        migrations.AddConstraint(
            model_name='varreview',
            constraint=models.CheckConstraint(condition=models.Q(('decision__in', ['confirmed', 'overturned', 'changed'])), name='valid_var_review_decision'),
        ),
    ]
