# Generated by Django 5.2.17 on 2026-09-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0030_injury_penaltyattempt_varreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchsubstitution',
            name='reason',
            field=models.CharField(choices=[('tactical', 'Tactical'), ('injury', 'Injury')], default='tactical', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='matchsubstitution',
            constraint=models.CheckConstraint(condition=models.Q(('reason__in', ['tactical', 'injury'])), name='valid_substitution_reason'),
        ),
    ]
