# Generated by Django 5.2.17 on 2026-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0031_matchsubstitution_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_head_coach_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_head_coach_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
