# Generated by Django 5.2.17 on 2026-09-12 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_match_statistics(apps, schema_editor):
    Match = apps.get_model('matches', 'Match')
    Goal = apps.get_model('matches', 'Goal')
    PenaltyAttempt = apps.get_model('matches', 'PenaltyAttempt')

    for match in Match.objects.iterator():
        active_goals = Goal.objects.filter(
            match_id=match.id,
            disallowed_at__isnull=True,
        ).exclude(goal_type='own_goal')
        penalty_attempts = PenaltyAttempt.objects.filter(match_id=match.id)

        home_saved_penalties = penalty_attempts.filter(
            team_side='home',
            outcome='saved',
        ).count()
        away_saved_penalties = penalty_attempts.filter(
            team_side='away',
            outcome='saved',
        ).count()

        Match.objects.filter(id=match.id).update(
            home_shot_count=(
                active_goals.filter(team_side='home').count()
                + penalty_attempts.filter(team_side='home').count()
            ),
            away_shot_count=(
                active_goals.filter(team_side='away').count()
                + penalty_attempts.filter(team_side='away').count()
            ),
            home_shot_on_target_count=(
                active_goals.filter(team_side='home').count()
                + home_saved_penalties
            ),
            away_shot_on_target_count=(
                active_goals.filter(team_side='away').count()
                + away_saved_penalties
            ),
            home_save_count=away_saved_penalties,
            away_save_count=home_saved_penalties,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0032_match_away_head_coach_name_and_more'),
        ('teams', '0005_team_head_coach_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CornerKick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_corner_kicks',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Foul',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_fouls',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offside',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_offsides',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('player_name', models.CharField(max_length=200)),
                ('goalkeeper_name', models.CharField(blank=True, max_length=200, null=True)),
                ('outcome', models.CharField(choices=[('off_target', 'Off Target'), ('saved', 'Saved'), ('blocked', 'Blocked'), ('woodwork', 'Woodwork')], max_length=15)),
                ('period', models.CharField(choices=[('first_half', 'First Half'), ('halftime', 'Halftime'), ('second_half', 'Second Half'), ('extra_time_first_half', 'Extra Time First Half'), ('extra_time_halftime', 'Extra Time Halftime'), ('extra_time_second_half', 'Extra Time Second Half')], max_length=25)),
                ('minute', models.PositiveSmallIntegerField()),
                ('added_minute', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_shots',
                'ordering': ['minute', 'added_minute', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_corner_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_foul_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_offside_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_save_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_shot_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_shot_on_target_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_corner_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_foul_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_offside_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_possession_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_save_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_shot_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_shot_on_target_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_match_statistics,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_possession_percentage__isnull', True), ('home_possession_percentage__lte', 100), _connector='OR'), name='valid_home_possession_percentage'),
        ),
        migrations.AddField(
            model_name='cornerkick',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corner_kicks', to='matches.match'),
        ),
        migrations.AddField(
            model_name='cornerkick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corner_kicks', to='teams.player'),
        ),
        migrations.AddField(
            model_name='foul',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fouls', to='matches.match'),
        ),
        migrations.AddField(
            model_name='foul',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fouls', to='teams.player'),
        ),
        migrations.AddField(
            model_name='offside',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offsides', to='matches.match'),
        ),
        migrations.AddField(
            model_name='offside',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offsides', to='teams.player'),
        ),
        migrations.AddField(
            model_name='shot',
            name='goalkeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saved_shots', to='teams.player'),
        ),
        migrations.AddField(
            model_name='shot',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='matches.match'),
        ),
        migrations.AddField(
            model_name='shot',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shots', to='teams.player'),
        ),
        migrations.AddConstraint(
            model_name='cornerkick',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_corner_kick_team_side'),
        ),
        migrations.AddConstraint(
            model_name='cornerkick',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_corner_kick_minute'),
        ),
        migrations.AddConstraint(
            model_name='cornerkick',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_corner_kick_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='cornerkick',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_corner_kick_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='foul',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_foul_team_side'),
        ),
        migrations.AddConstraint(
            model_name='foul',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_foul_minute'),
        ),
        migrations.AddConstraint(
            model_name='foul',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_foul_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='foul',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_foul_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='offside',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_offside_team_side'),
        ),
        migrations.AddConstraint(
            model_name='offside',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_offside_minute'),
        ),
        migrations.AddConstraint(
            model_name='offside',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_offside_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='offside',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_offside_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.CheckConstraint(condition=models.Q(('team_side__in', ['home', 'away'])), name='valid_shot_team_side'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.CheckConstraint(condition=models.Q(('minute__gte', 1), ('minute__lte', 120)), name='valid_shot_minute'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minute__gte', 1), ('minute__lte', 45), ('period', 'first_half')), models.Q(('minute__gte', 46), ('minute__lte', 90), ('period', 'second_half')), models.Q(('minute__gte', 91), ('minute__lte', 105), ('period', 'extra_time_first_half')), models.Q(('minute__gte', 106), ('minute__lte', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_shot_period_minute'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.CheckConstraint(condition=models.Q(('added_minute', 0), models.Q(('minute', 45), ('period', 'first_half')), models.Q(('minute', 90), ('period', 'second_half')), models.Q(('minute', 105), ('period', 'extra_time_first_half')), models.Q(('minute', 120), ('period', 'extra_time_second_half')), _connector='OR'), name='valid_shot_added_minute'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['off_target', 'saved', 'blocked', 'woodwork'])), name='valid_shot_outcome'),
        ),
        migrations.AddConstraint(
            model_name='shot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('goalkeeper__isnull', False), ('goalkeeper_name__isnull', False), ('outcome', 'saved')), models.Q(models.Q(('outcome', 'saved'), _negated=True), ('goalkeeper__isnull', True), ('goalkeeper_name__isnull', True)), _connector='OR'), name='valid_shot_goalkeeper'),
        ),
    ]
