# Generated by Django 5.2.17 on 2026-09-12 20:55

from django.db import migrations, models


def backfill_card_statistics(apps, schema_editor):
    Match = apps.get_model('matches', 'Match')
    Card = apps.get_model('matches', 'Card')

    for match in Match.objects.iterator():
        active_cards = Card.objects.filter(
            match_id=match.id,
            rescinded_at__isnull=True,
        )

        Match.objects.filter(id=match.id).update(
            home_yellow_card_count=active_cards.filter(
                team_side='home',
                card_type='yellow',
            ).count(),
            away_yellow_card_count=active_cards.filter(
                team_side='away',
                card_type='yellow',
            ).count(),
            home_red_card_count=active_cards.filter(
                team_side='home',
                card_type='red',
            ).count(),
            away_red_card_count=active_cards.filter(
                team_side='away',
                card_type='red',
            ).count(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0033_cornerkick_foul_offside_shot_match_away_corner_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_red_card_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_yellow_card_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_red_card_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_yellow_card_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(
            backfill_card_statistics,
            migrations.RunPython.noop,
        ),
    ]
