# Generated by Django 5.2.17 on 2026-09-13 18:36

from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone


def initialize_existing_match_clocks(apps, schema_editor):
    Match = apps.get_model("matches", "Match")
    period_base_minutes = {
        "first_half": 0,
        "halftime": 0,
        "second_half": 45,
        "extra_time_first_half": 90,
        "extra_time_halftime": 90,
        "extra_time_second_half": 105,
    }
    closed_periods = {"halftime", "extra_time_halftime"}

    for match in Match.objects.exclude(status="scheduled").iterator():
        base_minute = period_base_minutes.get(match.current_period)
        if base_minute is None or match.current_minute is None:
            continue

        elapsed_minutes = max(0, match.current_minute - base_minute)
        elapsed_minutes += match.current_added_minute
        reference = match.finished_at or timezone.now()
        match.period_started_at = reference - timedelta(minutes=elapsed_minutes)
        match.period_ended_at = (
            reference
            if match.status == "finished" or match.current_period in closed_periods
            else None
        )
        match.announced_added_minutes = match.current_added_minute
        match.clock_version = 1
        match.save(
            update_fields=[
                "period_started_at",
                "period_ended_at",
                "announced_added_minutes",
                "clock_version",
            ]
        )


def clear_match_clocks(apps, schema_editor):
    Match = apps.get_model("matches", "Match")
    Match.objects.update(
        period_started_at=None,
        period_ended_at=None,
        announced_added_minutes=0,
        clock_version=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0034_match_away_red_card_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='announced_added_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='clock_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='period_deadline_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='period_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='period_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='regulation_time_alerted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(initialize_existing_match_clocks, clear_match_clocks),
    ]
